### ISSUE TITLE
Iam facing issues on running this code in Windows. i know this is for unix but iam a fresher thats why ?

### ISSUE THREAD

**Issue by arjunvofficial** [yusufsyaifudin/go-kafka-example#1]
assigning value to MY_IP  makes issue

**Comment by arjunvofficial** [comment]
assigning value to MY_IP  makes issue

**Comment by yusufsyaifudin** [comment]
hi @arjunvofficial  have you tried to hard coded it in docker-compose.yml file? afaik, the MY_IP needed by `confluentinc/cp-kafka:5.0.0` docker image to route the network access using host connection

**Comment by arjunvofficial** [comment]
yeah, it worked thanx. :)
