### ISSUE TITLE
Do I need to close connection?

### ISSUE THREAD

**Issue by ALTELMA** [yusufsyaifudin/go-kafka-example#2]
Thanks for the nice article from medium.com, But I have some questions about your example code.

In this [config](https://github.com/yusufsyaifudin/go-kafka-example/blob/accadecfca65c956bf03a6199ff1f3944bc6d7dc/dep/kafka/config.go), I wondering should be added a close connection, right?

After we use [Push](https://github.com/yusufsyaifudin/go-kafka-example/blob/accadecfca65c956bf03a6199ff1f3944bc6d7dc/dep/kafka/push_message.go)

Please suggest to me :)

**Comment by yusufsyaifudin** [comment]
sorry for late reply @ALTELMA , afaik we only need to close connection only after we don't need it anymore, that is when we exit the program or when program is crashed. Thus I put the close connection in defer mode in the starting point code https://github.com/yusufsyaifudin/go-kafka-example/blob/accadecfca65c956bf03a6199ff1f3944bc6d7dc/cmd/api/main.go#L46
